plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-babel-release-tool.cjs
    spec: "@yarnpkg/plugin-babel-release-tool"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferInteractive: true

releaseTool:
  ignoreChanges:
    - "**/*.md"
    - "**/*.txt"
    - "**/__test__"
    - "**/*.test.*"
    - "**/*.spec.*"
    - /assets
    - /dist
    - /test
    - /tools

yarnPath: .yarn/releases/yarn-2.4.2.cjs
